language: android
dist: trusty
android:
  components:
  #Uncomment the lines velow to use the latest revision of Android SDK Tools
  #- tools
  #- platform-tools
  
  #The BuildTools version used by the project
  - build-tools-29.0.1
  
  #The SDK version used to compile the project
  - android-28
  
  #Additional components
  - extra-google-goole_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  
  #Specifying a system image for the tests that need the emulator
  - sys-img-x86-android-28
  - sys-img-armeabi-v7a-android-17

  #These two lines exist in order to get around the permission error
before_script:
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./licenses/* "$ANDROID_HOME/licenses/"
  - chmod +x gradlew
  
script:
  #- chmod +x ./gradlew build connectedCheck
  
  #Default test command for gradle file
  - ./gradlew clean build
